//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMHE.MO.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public long EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public string DisciplineCode { get; set; }
        public Nullable<bool> PS { get; set; }
        public Nullable<bool> TL { get; set; }
        public Nullable<bool> PL { get; set; }
        public Nullable<bool> QC { get; set; }
        public Nullable<bool> PM { get; set; }
        public Nullable<bool> HOD { get; set; }
        public Nullable<bool> TE { get; set; }
        public Nullable<bool> Status { get; set; }
        public string ProjectID { get; set; }
    }
}
